### ISSUE TITLE
Statusline's width is set to total combined screen width.

### ISSUE THREAD

**Issue by alspore** [Lokaltog/candybar#16]
Screenshot from recent commit.

![2014-02-27-165519_1920x26_scrot](https://f.cloud.github.com/assets/1596161/2288449/dd0ee488-9ff9-11e3-8df9-51c6cd48f16e.png)

Screenshot after changing `dim.w = 1920`.
![2014-02-27-165853_1920x26_scrot](https://f.cloud.github.com/assets/1596161/2288482/5e2c40ba-9ffa-11e3-95ad-53c432bb8c20.png)

It turns out that `screen->width_in_pixels` outputs `5760`, which is the total combined width of my three monitors.  Despite this the window only appears on one monitor.

**Comment by Lokaltog** [comment]
Hm, that's a bit weird, I thought XCB retrieved the dimensions from only one screen since it [enumerates the screens](https://github.com/Lokaltog/wkline/blob/develop/src/wkline.c#L62). Are you using xinerama? I don't have multiple monitors myself so I'm not sure how to work on fixing this, but feel free to look into it if you're up for the task.

**Comment by alspore** [comment]
Nope, I'm using RandR, though I only seem to have one screen.  This seems more like an issue with my particular system.  I'll definitely look into it.

EDIT: Never mind, RandR acts very similarly to Xinerama in that it combines multiple displays into a single screen.  This means you have to go through RandR or Xinerama to distinguish between monitors.

**Comment by ricardomv** [comment]
yes on i3 whith two monitors i get a black bar i guess the other part is in the other monitor to the left. 1 monitor works fine

**Comment by Lokaltog** [comment]
Is the issue fixed in #23?

**Comment by alspore** [comment]
Yup.  I sent a pull request to ricardo adding multi monitor support to his wayland branch as well.
