### ISSUE TITLE
Communicate with webview using JavaScriptCore instead of passing JSON data

### ISSUE THREAD

**Issue by Lokaltog** [Lokaltog/candybar#20]
http://rvr.typepad.com/wind/2011/10/webkit-extending-javascript-3.html

**Comment by Lokaltog** [comment]
@ricardo-vieira Continuing this in this issue:

> i don't know i didn't look into the json interface yet, but dbus never let me down. if every widget spawned a new interface that would be great and very easy to debug

I don't think we need to use dbus internally for IPC, but if it's possible to wrap the dbus functionality in an easy to use api it's fine with me. But I really don't want to have all the current boilerplate code for every widget.

Regarding javascriptcore I'm thinking that we could do something like this (just quick ideas, not sure if it's possible to do it just like this):
- Make a `Widgets` object available in the webview through JavaScriptCore
- In the theme JS, add event handlers for the `Widgets` object, e.g. `Widgets.volume.onUpdate(function() {[update volume bar here]})`
- Create a C function for proxying data to widgets, similar to the current `update_widget` function
- Instead of sending JSON data, widgets pass arrays of data to the `update_widget`, like `update_widget("volume", *volume_data_array)`
- `update_widget` passes `volume_data_array` to the JS event handler which updates the widget in the webview

Now for events happening in the webview:

When a user clicks e.g. "show /dev/sda1" in the HDD widget, the theme JS runs something like `Widgets.hdd.setDisplay('/dev/sda1', true)`. This method is defined by JavaScriptCore, and is being handled by the C backend. The backend can now handle this event by updating the configuration, provide data for the new HDD, save the config as JSON to the config file, etc.

Not sure if I'm explaining this clearly, and I may be overthinking this. What do you think?

**Comment by Lokaltog** [comment]
Regarding IPC with dbus: This could possibly be useful for decoupling the statusline and the widget daemon, and to provide widget data to other services. Projects like Powerline could also subscribe to widget data from the wkline daemon via dbus, and the other way around, other projects could provide data to wkline via dbus. I'm still not sure if it's worth it or not.

**Comment by ricardomv** [comment]
hey, finaly got rid of college work, i gess this is going to be a fun weekend. For the clicks in the bar every widget could have a signal "clicked" and the c part would only listen for the ones which we care, but lets focus first on porting the funcionality we have.

**Comment by ricardomv** [comment]
Did you got the example in the link to work i just get "Unable to load page"?

**Comment by Lokaltog** [comment]
Nice, I'm looking forward to working more on this project this weekend!

I didn't try to compile the example in the link, but I did create a battery widget based on dbus-glib. I'll do some experimenting with javascriptcore tomorrow.

**Comment by ricardomv** [comment]
i got it, had to change the path to the html file for some reason the relative path didn't work

**Comment by ricardomv** [comment]
you got it working already? O_o

**Comment by Lokaltog** [comment]
Nah, not the javascriptcore stuff, just dbus-glib for fetching battery info (see 9cfac92176c4694636403a02093c60ea0a474f26, I used a bunch of the code from the link). I noticed dbus-glib had much less boilerplate code so I thought I'd try to port the notification daemon widget tomorrow.

**Comment by ricardomv** [comment]
do you need the event handlers for the Widgets to all be the same (onUpdate)? we can have a class Battery with a method getVoltage and another getPercent which has a parent class Widgets that was the onclicked event. We will get rid of the threads and let the java call the c code.
the code for a widget would be something like [this](https://gist.github.com/ricardo-vieira/9283362)

**Comment by ricardomv** [comment]
oh but we need to update the widget from time to time. Can you make the call be repeated in java, we can set the time to repeat in a static value of the class

**Comment by Lokaltog** [comment]
It's possible to do checks on an interval in Javascript, but would it work to remove threading from the C code? For widgets that don't run on a timer like the volume and mpd widgets (waiting for changes), running on a timer would mean much more lag and unnecessary resource usage for checks when there are no state changes.

**Comment by ricardomv** [comment]
we can block on the c part like we do in threads and in the javascript you can make an infinite loop for that call. Does that make sense?

**Comment by Lokaltog** [comment]
I think I understand what you mean, but JS isn't threaded so blocking and waiting for input from C in a while loop in JS will lock the entire UI. JS is based on callbacks and event handlers, which is why I felt that registering callbacks in JS would be a cleaner solution than having it the other way around.

**Comment by ricardomv** [comment]
did you saw [this](http://rvr.typepad.com/wind/2011/11/webkit-extending-javascript-4.html) example? The battery recives update signals

```
 var battery = new Battery();
    battery.onChange = display;
    display();
```

**Comment by Lokaltog** [comment]
Nope, I didn't realize you could add a callback to that property. That's pretty neat, we should implement that.

**Comment by ricardomv** [comment]
i dont know how i am going to test this. maybe you can make a branch in wkline-theme with the new api.

**Comment by ricardomv** [comment]
for now i think we can do something simple like have an update signal in every widget and a function for every value we need in the ui much like the battery example. Later we can add the onclick events
