### ISSUE TITLE
Thoughts on dynamic widgets?

### ISSUE THREAD

**Issue by nHurD** [Lokaltog/candybar#26]
What's everyone's thoughts on making each widget a loadable library and added to the global collection upon application initialization? This way, if someone else wants to write a widget, it won't require a complete recompile of the application?

I was planning on implementing something like this by using [GModule](https://developer.gnome.org/glib/2.37/glib-Dynamic-Loading-of-Modules.html) to handle this.

**Comment by ricardomv** [comment]
yes i would like to have something like this. we can have every widget as a plugin that we can enable or disable, and can have swapable widgets that report to the same ui icon but have diferent backends like the volume widget for alsa and pulseaudio

**Comment by Lokaltog** [comment]
Sounds like an excellent idea. I'm all for making wkline more user friendly, and loadable third-party libraries is a great way to make it easier to write your own widgets, and a way for us to not have to include every single plugin in the main repo. I'm a bit busy this week so I'm not sure how much I can work on this, so feel free to start on this feature if you guys have time.

**Comment by nHurD** [comment]
Ok, I should have some downtime this week to take a stab at it.

**Comment by alspore** [comment]
I've been toying with the idea of writing widget back ends in something like lua or python, and then executing them with an embedded interpreter.  As long as it's not to resource intensive, would others support this?

**Comment by Lokaltog** [comment]
My vote is no, part of the reason why I ported the widgets from Python to begin with was to avoid the overhead of launching an interpreter and having that run in the background. I don't think coding the widgets in C is a huge hassle since they don't require much code to begin with. With e.g. Python you also may end up having to run shell commands to retrieve system data instead of using low-level libraries to fetch the data directly, which both requires more dependencies, have even more overhead and on top of that you have to parse the command output. If we were to go back to Python-based widgets we might as well just pipe output from Powerline into wkline or use Powerline widgets directly (see Lokaltog/powerline#816).

**Comment by Lokaltog** [comment]
I'm reading up on shared libraries, but there's quite a bit of stuff I don't know best practices for (like how to configure autotools and how to actually load the libraries), so if you guys can handle this  I'll continue working on the theme and more widgets in the meantime.

**Comment by nHurD** [comment]
I've got automake wired to generate shared libraries. Now it's just a matter of splitting out the sources and building accordingly

**Comment by Lokaltog** [comment]
Nice! Looking forward to seeing the results!

**Comment by nHurD** [comment]
I've been working on separating the widgets into libraries (see my [modules](https://github.com/nHurD/wkline/tree/modules) branch for more details). I'm currently coming up with an API for adding them at startup. My initial thoughts are to require each module have a function called `wkline_widget_init` that will load configuration data and add itself to the global collection of widgets.

**Comment by Lokaltog** [comment]
That sounds good, `wkline_widget_init` seems like a good name for it. I did a bit of refactoring on the develop branch today, I may have to revert those changes if your branch and @ricardo-vieira's latest changes conflict a lot with my changes. I basically moved a bit of widget code out of `wkline.c` and improved the thread spawning to avoid having to rely on global state so much.

**Comment by Lokaltog** [comment]
Looks like you've been able to merge develop without conflicts, that's good news. I'm trying to not mess too much with the develop branch until your changes have been merged.

**Comment by nHurD** [comment]
There were a couple of issues with the merge, but I managed to get it working again!

**Comment by Lokaltog** [comment]
Excellent! With shared libraries and the improved config I think we're getting really close to an initial release.

**Comment by ricardomv** [comment]
this is going to be fun :D three way merge. @Lokaltog i changed a bit thread spawning in my json-config branch i need to pass a `wkline_widget_t` struct to the threads. maybe let the threads start as it is. when we implement the javascriptcore it will be gone anyway.

**Comment by ricardomv** [comment]
@nHurD you might want to take a look at my branch jscore at the way i start the widgets, i think you are going to like it. it's just calling a function
Edit: the calls are in `widgets.c`

**Comment by nHurD** [comment]
Ok. I'll take a look at that. I'll also merge the config branch into my modules branch so we won't have too many merge conflicts when everything gets put together..

**Comment by Lokaltog** [comment]
@nHurD Just a heads up, I had to revert some of the refactoring in develop, and the JSON config branch has been merged. I've updated and re-applied the refactoring changes, but you may need to merge develop into your module branch and do some conflict resolving, as all the widget function signatures have been changed and all the typedefs have been converted into structs.

Edit: To clarify: you may need to revert 8136cfd0d56c67b980e21e6159a40d3b163c9e60.

**Comment by nHurD** [comment]
Thanks for the head's up! I only had one small merge conflict within my modules branch, everything else came over just fine. :beer:

**Comment by Lokaltog** [comment]
Have you done any more work on your branch? I have some time to work on the project today, so I can start implementing the module loading if you haven't started on it yet.

**Comment by nHurD** [comment]
I'm trying to decide when and where to load the modules. Initially, I was going to build the collection from a function call within main, that way the global collection will be available for other methods / callbacks.

I'm also trying to decide how to go about auto-loading of the plugins..

**Comment by Lokaltog** [comment]
I was thinking that we could maybe do this in a `wkline_reload` function that can be run at any time. That way we can later on support dragging configs onto the statusline and reload on the fly. This function could also handle thread spawning and all that stuff, similar to what `window_object_cleared_cb` does currently. We'll have to do some more work around that to make it possible to actually kill child threads (currently they wait without a timeout).

Regarding auto-loading, don't bother. I think we'll go for an array in config.json after all, with an ordered list of enabled widgets in addition to the config object.

**Comment by nHurD** [comment]
Ok, I was reading up on autoconf and automake to place the widgets into a subdirectory of $PEFIX/lib/wkline. I was then going to just scan that directory, load the module and call its init function to determine if it should be enabled or not.

**Comment by Lokaltog** [comment]
I think it'd be much simpler to just load widgets based on the json config, then the widgets won't have to include functionality to relay whether they're enabled or not back to the widget loader function. What do you think?

**Comment by nHurD** [comment]
Yeah, that makes much more sense. I'll still place the widgets into a common directory, however, so it's neater when its installed.

**Comment by Lokaltog** [comment]
Sounds good! Where do you plan to put the libs, and how will the wkline executable know where they are? (every distro has it's own global lib directory, and it would be nice if it supported relative directories as well so it would be possible to run wkline without installing it globally) I tried to search for more info on the topic, but autotools is the most confusing and complex piece of software I've ever come across, and I have absolutely no idea where to start.

**Comment by nHurD** [comment]
Right now, I have them going into $PREFIX/lib/wkline (see https://github.com/nHurD/wkline/commit/696ba1ebe403238646a963cb3583c8652aa6eb52 for more details). Then, I'll setup config.h to point to that directory. and pass that to `g_module_open()` to load the plugins. I think the crux of the issue will be naming the widget libraries to the name of the widget itself. For instance, weather will be named libweather.so and so on and so forth. I'd like to find a much more elegant solution, and if anyone has one, I'm definitely all ears

**Comment by Lokaltog** [comment]
I think the name would be more descriptive and elegant if it was e.g. `libwidget_weather.so` instead. It makes a bit more sense in my mind at least ("`libwidget` + whatever widget the library is for").

Passing the widget dir to configure seems like a good idea. For packages (like the arch linux package), should we put the widgets in `/usr/lib` or do they belong somewhere else? If we're putting them in a system directory we should probably prefix them with the project name too (like `libwkline_widget_weather.so`).

**Comment by nHurD** [comment]
I have the widgets going into a subdir labeled wkline. So for packages, it'd go under `/usr/lib/wkline/`

**Comment by Lokaltog** [comment]
Ah, I can see that it's fine to put stuff in a subdir in `$libdir`, so naming the widgets like `$libdir/wkline/libwidget_weather.so` should work well.

**Comment by Lokaltog** [comment]
Man, I can't wait to merge this feature, it's really exciting stuff!

**Comment by nHurD** [comment]
Just thought I'd give a small status report: I've got the modules loading, but am now hunting down why the individual threads aren't executing. I've pushed my latest set of changes to my modules branch in case someone wants to have a look or take a stab at it.

**Comment by Lokaltog** [comment]
I did a quick experiment a couple of days ago, and was able to spawn a thread successfully. It was just a quick experiment with a predefined widget to see how it worked, here's the diff:

``` diff
diff --cc src/widgets/widgets.c
index 64502ed,64502ed..6301e73
--- a/src/widgets/widgets.c
+++ b/src/widgets/widgets.c
@@@ -1,7 -1,7 +1,9 @@@
  #include "widgets.h"
  #include "../wkline.h" // required for struct wkline
++#include <gmodule.h>

  GThread *widget_threads[LENGTH(wkline_widgets)];
++typedef void (* widget_volume_func) (struct widget *widget);

  gboolean
  update_widget (struct widget *widget) {
@@@ -34,6 -34,6 +36,21 @@@ window_object_cleared_cb (WebKitWebVie
        struct wkline *wkline = user_data;
        unsigned short i;

++      widget_volume_func widget_volume;
++      GModule *libvolume = g_module_open("libvolume.la", 0);
++
++      if (!g_module_symbol (libvolume, "widget_volume", (gpointer *)&widget_volume)) {
++              wklog("failed");
++      }
++                      struct widget *widget = malloc(sizeof(struct widget));
++
++                      widget->config = wkline->config;
++                      widget->web_view = web_view;
++                      // Dont forget to free this one
++                      widget->name = strdup("volume");
++
++                      widget_threads[0] = g_thread_new("volume", (GThreadFunc)widget_volume, widget);
++
        wklog("webkit: window object cleared");
        for (i = 0; i < LENGTH(wkline_widgets); i++) {
                // FIXME this is pretty bad, it should probably join and recreate the threads instead
```

Not sure if it's any help at all, I haven't had time to look at your latest changes yet.

**Comment by Lokaltog** [comment]
I've fully implemented working loadable modules [here](https://github.com/Lokaltog/wkline/compare/feature;loadable-modules).

There are a couple of things I want to improve before I merge it into develop. I'd love to hear if you have any better ideas for specifying the widget search path (i.e. `/usr/lib/wkline`), it works fine if you're installing it into a system path, but if you want to use relative paths (e.g. for development or testing), you currently need to pass a lib search path like described in a9f21088d2e5cdbef411dfe70d817715543ecf9c, as `g_module_build_path` receives an absolute system path from waf. It would be nice if there was a way to use a relative load path derived from $PREFIX or the install path for dev builds.

Another thing I want to implement is graceful thread shutdown so we can cleanup properly and prepare for on-the-fly config reloading (this requires thread respawning, and thread respawning requires a fairly short timeout on select/poll loops so the threads can respond to a kill signal).
