### ISSUE TITLE
util organization

### ISSUE THREAD

**Issue by Lokaltog** [Lokaltog/candybar#28]
After adding macros and utility functions, I was wondering what's best practice for organizing the util directory. Some of the code rely on standard macros like MIN, MAX, and quite a lot of #defines are being added all over the place (most of it my fault, I apologize for that).

Is it good practice to have e.g. a `macros.h` and `defines.h` in the util directory that can be included in `wkline.h` or something like that?

Also, when adding utility functions, should each function have a separate .c/.h file if the functionality falls under the "general function" category (like the copy_prop function I added earlier today)?

**Comment by ricardomv** [comment]
nah its going to be a mess if you need to do #include "util/macros.h" in every file you need macros just define them in the .h of the file you need the macro (as i think it is now). 
The defines too we already have a long compile time if we add every lib we need in every .c file we have the compilation time will increase exponentially.

**Comment by Lokaltog** [comment]
Allright, I'll leave it as it is now then.

Regarding compile time, would it be possible to not include every lib when compiling every C file, I've noticed the compile time starting to get a bit out of hand as I've been adding widgets. It would be nice not having to include `libmpdclient` in 20 C files that don't actually use libmpdclient. I'm guessing it's possible with autotools, what I'm really asking is if you know whether it's a lot of work implementing and maintaining such a change.

**Comment by ricardomv** [comment]
i think that if you only put the header of libmpd in one file it wont make much difference. i think the time we are seeing is the time the pre-processor `cpp` takes to copy the header files, not really compiling

**Comment by Lokaltog** [comment]
Roger that, I'll leave things as they are.
