### ISSUE TITLE
use autotools to install config.def.json

### ISSUE THREAD

**Issue by ricardomv** [Lokaltog/candybar#33]
does the name of the file has to be config.def.json? i can't change it's name in autotools an wkline only knows about config.json. also i'm trying to load the configfiles from systemconfig path /etc/xdg/wkline.
Bottom line is autotools should know about config.def.json and we should not end the program if we can't find the user configuration.

**Comment by Lokaltog** [comment]
Sure, we could name it config.json instead, and install it with autotools in /etc/xdg/wkline, that sounds like an excellent solution. Didn't really think about the possibility of installing it with autotools, but it makes sense, then we'll always have a fallback configuration too. Are you up for the task?

**Comment by ricardomv** [comment]
yes i'm doing it. almost done
