### ISSUE TITLE
Exchange autotools with something less annoying to configure?

### ISSUE THREAD

**Issue by Lokaltog** [Lokaltog/candybar#35]
I'm already fed up from using autotools and trying to understand the docs for it, it feels _way_ too overkill and complex for a small project like this one. When searching for other options I came across SCons, which seems like a pretty good alternative. I'm a bit biased since it's written in Python, but I'm willing to try anything if it means I won't have to look at m4 and makefiles again.

I'd like to hear some opinions if you guys have tried SCons before, if you have any other ideas, or if you have any really good arguments in favor of keeping autotools as our build system of choice.

Edit: link to [crash course](http://www.scons.org/wiki/SConsCrashCourse) showcasing a simple build script.

**Comment by ricardomv** [comment]
i always wanted to look into [waf](https://code.google.com/p/waf/) but i never had the chance. i'm going to do a bit of research (i'm sick of autotools too)

**Comment by Lokaltog** [comment]
waf looks even better and more pythonic, it might be the better choice. The docs appear really lacking compared to the SCons docs though, so it might be more difficult getting it working. I'll look into it as well.

**Comment by Lokaltog** [comment]
I think waf is the way to go, it feels intuitive and easy to work with (I also found better docs on it).

Ref #26 when we're making shared libraries it's as simple as exchanging `bld.stlib` with `bld.shlib` and it will automatically compile .so files instead of statically linked .a files.

**Comment by nHurD** [comment]
This sounds great. Once I figure out some issues I'm experiencing with the dynamic modules, I'll get it working under the new build system
