### ISSUE TITLE
Make LIBDIR configurable at runtime

### ISSUE THREAD

**Issue by Lokaltog** [Lokaltog/candybar#40]
There's really no reason why LIBDIR should be hardcoded at compile time. I'm implementing command-line argument parsing (to be able to define a custom config file), I'm thinking that we could include `--libdir` as a command-line argument, and fall back to the compile-time libdir if this argument isn't provided.

We could also support loading of widgets from arbitrary locations, e.g. by supporting absolute file paths in the widgets array in the config file.

**Comment by nHurD** [comment]
If anything, I think the LIBDIR should still be coded into the system to act as a default, and if a user provides an alternate path, then the application searches in both LIBDIR and that path for widgets...

**Comment by Lokaltog** [comment]
Absolutely, adding a configurable libdir would be in addition to the libdir provided at compile time.

**Comment by Lokaltog** [comment]
LIBDIR has been replaced by a rootdir configure argument. An alternative (if required in the future) may be to have a per-widget library path, to be able to load single third-party widgets located in a directory outside the library search path.
