### ISSUE TITLE
i3's desktop widget compatibility.

### ISSUE THREAD

**Issue by alspore** [Lokaltog/candybar#53]
I recently noticed that the desktops widget was consistently failing on i3wm.  After digging through the source for a bit I can't seem to find out why, though I did find a helper program called `i3-msg` which talks to the i3 instance using some sort of socketed ipc interface.  Do you think it's a bad idea to implement a fallback using i3's ipc interface as opposed to working on fixing the bug in i3 itself?

**Comment by Lokaltog** [comment]
Could you describe how it's failing? Does it just not render? If i3 doesn't provide the required EWMH properties we can't use the existing desktops widget. What we could do is rename the current desktops widget to `desktops_ewmh`, then create alternative widgets that provide the same information, but use the i3 socket interface instead. Another alternative is to include all the functionality in the desktops widget, and have a config.json option to change which WM you're using.

Not sure what's the best approach here, but there's a bunch of WMs that don't implement EWMH but have alternative ways of getting this information, it would be nice to be able to provide a desktop list or window name for these WMs as well.

One issue with this is that it must be possible to listen to this socket interface and wait for desktop change notifications. If not you'll have to do some kind of loop on an interval and query the socket for updated info all the time which may consume a bit of resources and not be instant.

You could report this as a bug to i3, or possibly provide a patch to i3 that sets the required EWMH properties, it would definitely be the best approach in my opinion.

**Comment by alspore** [comment]
It doesn't render and outputs `DEBUG ewmh: could not get current desktop (desktops.c)`.

**Comment by Lokaltog** [comment]
That means i3 doesn't support the `_NET_CURRENT_DESKTOP` EWMH property, which is a minimum to display which desktop is selected. This should ideally be implemented in i3, but they may have some filosophy like the dwm authors have in that minimalism is great and bells and whistles like EWMH is bad. You could open an issue or search and see if there's a reason why they don't support EWMH hints, or if it's just that they haven't had time/reason to implement it yet.

**Comment by Lokaltog** [comment]
Hmm. Judging by [this](http://code.stapelberg.de/git/i3/tree/src/ewmh.c#n21) you'd think i3 supports this property. It's not included in the root window properties though. Here's my output from `xprop -root` in Xephyr:

```
I3_SHMLOG_PATH(UTF8_STRING) = 
I3_CONFIG_PATH(UTF8_STRING) = "/home/kim/.i3/config"
I3_PID(CARDINAL) = 11143
I3_SOCKET_PATH(UTF8_STRING) = "/run/user/1000/i3/ipc-socket.11143"
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_WM_NAME, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_DESKTOP, _NET_WM_STRUT_PARTIAL, _NET_CLIENT_LIST_STACKING, _NET_CURRENT_DESKTOP, _NET_ACTIVE_WINDOW, _NET_STARTUP_ID
_NET_WM_NAME(UTF8_STRING) = "i3"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x20000b
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
```

It even claims to support `_NET_CURRENT_DESKTOP` but it doesn't actually provide the property. This might be a bug in i3.

**Comment by alspore** [comment]
I'm almost done implementing a `desktops_i3` widget as a `desktops_ewmh` alternative.  I'm currently finding the socket path by using popen to run the `i3 --get-socketpath` command.  Unfortunately the socket file changes location every couple of restarts, so it looks like this might have to be permanent.

**Comment by Lokaltog** [comment]
Awesome, looking forward to checking it out!

**Comment by alspore** [comment]
So I've been working in my i3-ipc branch and I've managed to setup helper libraries for communicating with i3's ipc protocol, though I'm having trouble integrating the functionality into a drop in replacement for the newly named `desktops_ewmh` widget.  Would you be able to take a look at it?  I'd be happy to explain my additions.

PS: I'm starting to get the suspicion that I'm writing spaghetti code, so a second opinion would be awesome.

PSS: [Here's a link.](https://github.com/5paceManSpiff/wkline/tree/i3-ipc)

**Comment by Lokaltog** [comment]
Sure! I'm not exactly a veteran C coder myself but I think it looks pretty good, and it doesn't strike me as spaghetti code. It would be great if you could also run the code through uncrustify with the config file in the project root before sending a PR, it would save me a bit of work when merging it.

Regarding your trouble integrating the widget, what's the issue? My first guess would be that the theme doesn't recognize it as the desktop widget and refuses to render it, it's easy to test this by temporarily renaming the widget to just "desktops". I think we may need to create some sort of name override instead of using the name provided in config.json. A simple `const char *widget_name` in every `<widget>.c` that's imported when loading the .so could do the trick. That way we can have two desktop widgets with different names that still gets recognized as the same widget by the theme.

**Comment by alspore** [comment]
A name override would be helpful.  My problem integrating the widget is I'm having a bit of trouble wrapping my head around epoll, as well as I'm not quite sure if my widget data callback is formatted correctly.

**Comment by Lokaltog** [comment]
I see. I wrapped the epoll stuff in a macro as quite a bit of boilerplate code is required to include it in the widgets, and I couldn't get it working properly with a function. 

Does i3 push JSON data to the socket every time you switch desktops (i.e. you could just listen to events on the socket and handle them in the widget right when they occur), or do you have to manually query i3 every time?

**Comment by alspore** [comment]
I'll check out the epoll macro, as well as read a bit more into regular epoll usage.

I currently have it setup so i3 pushes changes in JSON to the socket after every time a workspaces switches focus.  I can also set this to update when workspaces become "urgent".  I'm not quite sure why the while loop in `widget_main` does this.  My first guess was that the function `i3_recv` blocked, but that doesn't seem to be so.

**Comment by Lokaltog** [comment]
If possible you should subscribe to the "urgent" events too, as the desktop widget will highlight/pulse urgent desktops.

If i3 pushes events to the socket I'd move the socket event handling to the while loop in `widget_main` and add the socket fd to the same epoll handler as the global eventfd (`wkline->efd`), similar to how it's done in the existing desktops widget:

As you can see on [this line](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/desktops.c#L145) the XCB file descriptor is added to the same epoll handler as the `efd` eventfd that's setup by the [`widget_epoll_init`](https://github.com/Lokaltog/wkline/blob/develop/src/widgets.h#L82) macro. By doing it this way you'll be able to [block and wait for events on two fds](https://github.com/Lokaltog/wkline/blob/develop/src/widgets/desktops.c#L153) (one being the [`eventfd`](https://github.com/Lokaltog/wkline/blob/develop/src/wkline.c#L173) that relays the thread cancel signals, the other one being the i3 event socket). Then you'll be able to handle either the thread cancel signal, or the i3 events inside the while loop.

I think it should be possible to keep the `i3_recv` function (it could look a bit cleaner having the event handling in a separate function) by returning the i3 fd from the i3 init function, then adding that fd to the epoll handler, and calling `i3_recv` (maybe rename it to `handle_i3_event` or something?) inside the main loop on i3 events like you do now. If you do it like this `i3_recv` should _not_ block, but rather consume and handle any events from the socket, return, then let the main loop block on `epoll_wait` until another event has been received. 

I apologize if I'm bad at explaining this stuff, let me know if anything's unclear or confusing and I'll try to explain it better!

**Comment by acrisci** [comment]
Check out [i3ipc-glib](https://github.com/acrisci/i3ipc-glib) - it's a C library for the i3 ipc.

**Comment by acrisci** [comment]
Or actually, I'm working on implementing most of these ewmh properties in i3 right now so that might be enough.

**Comment by Lokaltog** [comment]
It would definitely be ideal if i3 would support EWMH properties in addition to having its own IPC protocol, to avoid having to treat it as a special case and introduce extra dependencies.

**Comment by acrisci** [comment]
@Lokaltog 
Ok, can you make an issue on http://bugs.i3wm.org and let me know which ones you need? (just so I don't overlook anything)

If you want to support click events to change desktops, I think we would need to implement the _NET_WM_DESKTOP client request.

Surprisingly nobody has requested this feature through the official channels.

**Comment by Lokaltog** [comment]
Will do! I'm not sure if the `_NET_WM_DESKTOP` client request is supported by any common tiling WM, I've tried getting it to work with xcb-wm but I haven't had any success with any of the WMs I've tested it with.

**Comment by Lokaltog** [comment]
Added support ticket at bugs.i3wm.org: http://bugs.i3wm.org/query/ticket/1241

**Comment by alspore** [comment]
In the mean time I'll check out i3ipc-glib because my current implementation is not the most stable thing.

Also, sorry for the delayed development.  I'm still working on this, just slowly.

**Comment by alspore** [comment]
#70 add's the replacement `desktops` plugin.

**Comment by Lokaltog** [comment]
Closing this as it's resolved for candybar, and the desktops widget should work out of the box once i3 implements EWMH properties.
