### ISSUE TITLE
Wkline crashes after mpd is killed.

### ISSUE THREAD

**Issue by alspore** [Lokaltog/candybar#54]
Wkline crashes after mpd is killed if mpd was running when wkline was started.

**Comment by alspore** [comment]
Here's a gist of the command line output.

https://gist.github.com/5paceManSpiff/9553611

**Comment by Lokaltog** [comment]
Hmmmm. This looks related to b3d5733de268444a4bb13db101b5970b712a0655, I might have gone a bit overboard clearing memory here. I'm guessing that the connection pointer [here](https://github.com/Lokaltog/wkline/commit/b3d5733de268444a4bb13db101b5970b712a0655#diff-4fc4f0fdb5bd06c18869529e187f52a8R128) may be not NULL even if the connection has never been successful or if the connection is cancelled. I'll look into it!
