### ISSUE TITLE
Project name suggestions

### ISSUE THREAD

**Issue by Lokaltog** [Lokaltog/candybar#58]
I'm not great at naming projects, and "wkline" is a placeholder name I used when creating the repo. I'm not a fan of the name but don't really know what else I'd name the project, do any of you guys have any suggestions?

**Comment by Lokaltog** [comment]
I think I'm going to rename the project to "candybar" (fits with "eye-candy status bar" and sounds much better than wkline in my opinion). I can't find a similarly named project in the arch packages or on the AUR, so unless anyone's opposed to the new name (other than the hassle involved renaming the project) I'll go ahead and rename it.

**Comment by alspore** [comment]
While I don't think there are any Linux packages with the same name, I'd be
aware of the Mac icon switcher called candybar.

http://iconfactory.com/software/candybar

**Comment by Lokaltog** [comment]
Hmm, that's a valid point. But as it's a totally unrelated OSX-specific app, and the name is a common word, I don't think it should be an issue.

**Comment by alspore** [comment]
I agree.  Candybar is a great name.

**Comment by Jwpe** [comment]
This is a great name! :)

**Comment by Lokaltog** [comment]
Awesome, glad you guys like it!
