### ISSUE TITLE
snd_mixer_selem_get_playback_volume_ranger: Assertion `elem' failed.

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#71]
When running candybar-git as well, as the debug variant specified in your docs, I get this error while launching candybar: `candybar: simple.c:282: snd_mixer_selem_get_playback_volume_ranger: Assertion `elem' failed.`, which is promptly followed by candybar aborting.

Something of note: I use an external DAC and I've noticed that when It's not plugged in I don't get the error, but I do get this instead: `ERROR could not attach card 'default' to mixer (-2) (volume.c)`, although unlike the other error candybar doesn't abort.

For the record I use ALSA, in case that's important.

**Comment by Lokaltog** [comment]
It should definitely not crash, so this is a bug (the second error message is intended behavior, it basically logs that your DAC isn't connected). I'm not doing sanity checks at every step of the way in the volume widget (which I realize should be done). I'll look into adding more sanity checks, in the meantime you can disable the volume widget, this should resolve your crashing issue until this is fixed.

**Comment by ghost** [comment]
Thanks, that works fine.
