### ISSUE TITLE
High CPU usage using desktops_i3

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#75]
Shortly after launching candybar with the sole change being `desktops` replaced with `desktops_i3`, another candybar instance is spawned (according to htop 1.03 at least) and both of them shoot up to 100 percent CPU usage and remain there until candybar is killed. Candybar remains fully functional during this period, and no error messages are printed (same with a debug build).

This is all using a git build up to cabe5d4e89.

**Comment by alspore** [comment]
This is something I'm experiencing with `desktops_i3` as well. I'll look into it.

**Comment by alspore** [comment]
That seems to have fixed it on my end, how about you?

**Comment by ghost** [comment]
Works fine for me, that was quicker than expected. Thanks.
