### ISSUE TITLE
Incorrect battery reading after resume from suspend

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#79]
Here's the issue:
- Have candybar open and suspend via `systemctl suspend`
- Resume, and have  candybar say I have 0% battery

Candybar states I have 0% battery (with the accompanying red glowing background) for a decent amount of time afterwards, up to 15-20 seconds (I didn't time it, that's just approximately what I remember).

I'm running UPower, so perhaps UPower, or the underlying power information UPower is abstracting, isn't restored immediately, so UPower could be returning 0 as the battery's percentage if candybar is asking immediately on resume. One more thing of note is that I've never noticed this on short suspends, but if I don't use my computer for a few hours than this issue tends to pop up. For example, if I run `systemctl suspend` right now, and immediately proceed to resume, candybar works fine. Does candybar's battery interface operate on an event driven basis or a polling one?

I'm using the latest version available of candybar as of this issue's submission date.

**Comment by Lokaltog** [comment]
I'm not sure if this is a candybar error as it reads its information from dbus. candybar currently polls for changes, but changing this to listening to events is on the todo list. I'll leave this open until an event-driven battery widget has been implemented to see if that resolves this issue.
