### ISSUE TITLE
Namcap errors

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#80]
When running namcap on the output of candybar's PKGBUILD, I get a decent amount of errors. Here is namcap's output with the dependency errors removed for conciseness:

`Non-FHS man page (usr/man/man1/candybar.1.gz) found. Use /usr/share/man instead`
`Non-FHS man page (usr/man/man5/candybar.5.gz) found. Use /usr/share/man instead`
`File (usr/man/) exists in a non-standard directory.`
`File (usr/man/man5/) exists in a non-standard directory.`
`File (usr/man/man1/) exists in a non-standard directory.`
`File (usr/man/man1/candybar.1.gz) exists in a non-standard directory.`
`File (usr/man/man5/candybar.5.gz) exists in a non-standard directory.`
`Dependency gtk3 included but already satisfied`

gtk3 is an implicit dependency via webkitgtk, so just removing it from the PKGBUILD will fix it. As for the other errors I assume waf is responsible for those. Also, what do you think about putting the PKGBUILD in this repo @Lokaltog, as it is after all maintained in the AUR by you.

**Comment by Lokaltog** [comment]
Thanks for the report, I'll fix these errors right away. The PKGBUILD is available in my candybar-pkg-archlinux repo.

**Comment by Lokaltog** [comment]
I see that namcap reports warnings about the optional dependencies for all widgets with optional dependencies, I don't know how to fix this properly. candybar detects these dependencies during the build process so if you have an optional dependency installed candybar will build the corresponding widget, but namcap reports this as warnings:

```
candybar-git W: Dependency libmpdclient detected but optional (libraries ['usr/lib/libmpdclient.so.2'] needed in files ['usr/lib/candybar/libwidget_now_playing_mpd.so'])
candybar-git W: Dependency xcb-util-wm detected but optional (libraries ['usr/lib/libxcb-ewmh.so.2', 'usr/lib/libxcb-icccm.so.4'] needed in files ['usr/lib/candybar/libwidget_window_title.so', 'usr/lib/candybar/libwidget_desktops.so'])
candybar-git W: Dependency graphicsmagick detected but optional (libraries ['usr/lib/libGraphicsMagick.so.3'] needed in files ['usr/lib/candybar/libwidget_magick_background.so'])
candybar-git W: Dependency alsa-lib detected but optional (libraries ['usr/lib/libasound.so.2'] needed in files ['usr/lib/candybar/libwidget_volume.so'])
candybar-git W: Dependency curl detected but optional (libraries ['usr/lib/libcurl.so.4'] needed in files ['usr/lib/candybar/libwidget_external_ip.so', 'usr/lib/candybar/libwidget_email_imap.so', 'usr/lib/candybar/libwidget_weather.so'])
candybar-git W: Dependency playerctl detected but optional (libraries ['usr/lib/libplayerctl-1.0.so.0'] needed in files ['usr/lib/candybar/libwidget_now_playing_mpris.so'])
```

Do you have any suggestions to how this can be fixed?
