### ISSUE TITLE
Add WebKit web inspector while debugging.

### ISSUE THREAD

**Issue by alspore** [Lokaltog/candybar#86]
After tinkering with the default theme, I've found that it's a bit difficult to debug various quirks in widget callbacks without some way to dynamically interact with them.  Adding the debugger would make this process a good deal simpler.

**Comment by Lokaltog** [comment]
Yep, I agree about this one, and I've had it on my todo list but haven't gotten around to it yet. I think that we could add a `--debug` flag which launches a regular, resizable window with the web inspector enabled and open.

**Comment by alspore** [comment]
I've managed to get the inspector working, and am currently implementing it as optional functionality with the `--debug` flag.  If you'd like to check out what I have so far, it's on my `web-inspector` branch.
