### ISSUE TITLE
Update Makefile to disable widget based on missing dependencies?

### ISSUE THREAD

**Issue by Lokaltog** [Lokaltog/candybar#9]

**Comment by ricardomv** [comment]
hi, i am trying to port this to compile with autotools, later today i can send you a pull request

**Comment by Lokaltog** [comment]
Thanks, that sounds great!

**Comment by Lokaltog** [comment]
@ricardo-vieira Do you know if it's possible/easy to implement a way to pass DISABLE_[widget] flags to gcc and make this configurable by the user? E.g. running `./configure --without-widget_weather` passes `-DDISABLE_WEATHER` to gcc to disable the entire weather widget.

**Comment by ricardomv** [comment]
yes that was the next thing i was adding to the build system. autotools has a system you set a default (enable/disable) and it defines a symbol in config.h (not your config.h witch you should think in removing) and then you just do an #ifdef of that symbol. and you can disable it in configure with --disable-widget_weather or --enable-widget_weather. 
but i can't do it now it will have to wait until the weekend :|

**Comment by Lokaltog** [comment]
Allright, no rush, I'll see if I can get it to work in the meantime.

The plan is to remove config.h soon, but I'm not sure if I want to use a JSON config file or command-line arguments. I'm thinking about going for a JSON config file in e.g. `$XDG_CONFIG_HOME/wkline/config.json`. With a JSON config file we could possible reuse the config loading functionality for reloading the configuration when drag/dropping a theme from a website.

**Comment by ricardomv** [comment]
Do you realize the dnd function is already implemented? you can try it right now. I don't think you need to reload the config you just need to open a popup asking "Set as default? " and if yes just save it. you only need a function to load the config file, just make it reusable an use dynamic memory

**Comment by Lokaltog** [comment]
I tried dropping an URI onto the statusline, but it didn't do anything, what do you do to make it work?

**Comment by ricardomv** [comment]
It does not work as well as i thought it would. I think the widgets crash in the process. Are you selecting the text and dragging? just drag the url http://lokaltog.github.io/wkline-theme-default/

**Comment by Lokaltog** [comment]
Yep, I tried dragging it from chrome and from a text box, still doesn't work for me unfortunately. Maybe dropping is handled differently in various WMs. I'm guessing the WebView provides a signal for dropping that can be used to handle this properly.

**Comment by Lokaltog** [comment]
btw, found [this](https://www.flameeyes.eu/autotools-mythbuster/autoconf/arguments.html), trying to implement it now.

**Comment by ricardomv** [comment]
Yes that's what i was talking about.

**Comment by Lokaltog** [comment]
Man this is frustrating. I've managed to register the command-line argument, but it fails to build if a library is missing, because it still tries to build all the files in the source array in Makefile.am. Here's what I've got so far:

``` diff
diff --git a/configure.ac b/configure.ac
index 5fc0839..ee26f33 100644
--- a/configure.ac
+++ b/configure.ac
@@ -3,6 +3,17 @@ AM_INIT_AUTOMAKE([-Wall -Werror foreign subdir-objects])
 AC_PROG_CC
 AC_CONFIG_HEADERS([config.h])

+AC_ARG_WITH([mpd], AS_HELP_STRING([--without-mpd], [compile without libmpdclient support]))
+
+AS_IF([test "x$with_mpd" != "xno"],
+      [PKG_CHECK_MODULES([MPD], [libmpdclient], [have_libmpdclient=yes], [have_libmpdclient=no])],
+      [have_libmpdclient=no])
+
+AS_IF([test "x$have_libmpdclient" = "xyes"], [], [
+      AC_DEFINE([DISABLE_WIDGET_NOW_PLAYING_MPD], [], [disable libmpdclient])
+      AS_IF([test "x$with_mpd" = "xyes"], [AC_MSG_ERROR([libmpdclient requested but not found])])
+      ])
+
 # Remove if you wish to see full compiler command lines
 AM_SILENT_RULES([yes])

@@ -14,7 +25,6 @@ PKG_CHECK_MODULES([XCB], [xcb-util xcb-ewmh xcb-icccm])
 PKG_CHECK_MODULES([JSON_GLIB], [jansson])
 PKG_CHECK_MODULES([CURL], [libcurl])
 PKG_CHECK_MODULES([ALSA], [alsa])
-PKG_CHECK_MODULES([MPD], [libmpdclient])

 AC_CONFIG_FILES([
  Makefile
```

We only need to find a way to remove src/widgets/now_playing_mpd.c from the sources array in makefile.am for this to work.

Would it be possible to remove the widgets from the source array and do something like this instead in widgets.h?

``` c
#ifndef DISABLE_WIDGET_NOW_PLAYING_MPD
#include "now_playing_mpd.c"
#endif
```

I know you mentioned #including .c files was bad practice, do you have any suggestions to resolve this issue?

**Comment by ricardomv** [comment]
Use _SOURCES += file.c add one at a time

**Comment by ricardomv** [comment]
Did you get it?  Im on the phone i cant see the diff

**Comment by Lokaltog** [comment]
Yep, I'm on it, almost done with the patch now.
