### ISSUE TITLE
weather: "unit" : "f" returns non integer

### ISSUE THREAD

**Issue by ghost** [Lokaltog/candybar#90]
When telling the weather widget to use Fahrenheit instead of Celsius, a non integer is returned. Is candybar requesting Yahoo queries in Celsius regardless of the unit setting, and then just converting them locally and trimming to one decimal place? Briefly looking over the Yahoo weather API docs makes it seem like you can request what format you want your temperatures to be in your queries. Just to be clear (and this kind of goes without saying), weather should be presented as integers as anything more specific is useless given the current purpose of the output (quickly glancing at a number to get a general idea of the weather).

Sorry if I'm wrong in my assumptions, I attempted to understand weather.c, but that was pointless as I don't even know C.

**Comment by Lokaltog** [comment]
It [requests celsius](https://github.com/Lokaltog/candybar/blob/develop/src/widgets/weather.c#L55) from Yahoo! and [converts it locally](https://github.com/Lokaltog/candybar-theme-default/blob/develop/app/assets/js/utils.js#L34). Is the issue that the temperature isn't rounded to an integer when displayed in the statusline? I can't remember why I don't request Fahrenheit from Yahoo! instead (the weather request code has basically been copied from Powerline), I'll look into it.

**Comment by ghost** [comment]
Yes, the issue is that it isn't rounded.
